// Add any custom config to be passed to Jest
const customJestConfig = {
	testEnvironment: 'node',
	testTimeout: 10000,
	moduleDirectories: ['node_modules'],
	preset: 'ts-jest',
	setupFilesAfterEnv: [
		'<rootDir>/modules/database/database.module.mock.ts', 
		'<rootDir>/modules/database/redis.module.mock.ts'
	],
	transform: {
		'node_modules/variables/.+\\.(j|t)sx?$': 'ts-jest',
	},
	transformIgnorePatterns: ['node_modules/(?!variables/.*)'],
	modulePathIgnorePatterns: [
		'<rootDir>/dist/',
		'<rootDir>/controllers/',
		'<rootDir>/database/',
		'<rootDir>/modules/crons/task-queue.cron.ts',
		'<rootDir>/modules/crons/index.ts',
		'<rootDir>/src/__generated__/',
		'<rootDir>/src/config.ts',
		'<rootDir>/routes/',
		'<rootDir>/.babelrc.js',
		'<rootDir>/jest.config.js',
	],
	verbose: true,
	collectCoverage: true,
	collectCoverageFrom: [
		'!**/node_modules/**',
		'!**/bin/**',
		'!**/dist/**',
		'!**/controllers/**',
		'!**/*.test.ts',
		'!**/*.json',
		'!**/*.config.ts',
		'!**/app.ts',
		'!**/mock/**',
		'!**/coverage/**',
		'!**/prisma/**',
		'!**/modules/database/**',
		'!**/routes/**',
		'!**/src/enums/**',
		'!**/src/lib/**',
		'!**/src/types/**',
		'!**/src/telegram/variables.ts',
		'!**/src/services/onboarding.service.ts',
		'!**/modules/crons/task-queue.cron.ts',
		'!**/modules/gmail/**',
		'!**/modules/notifications/email.service.ts',
		'!**/modules/notifications/webpush.service.ts',
		'!**/modules/notifications/notification-preference.service.ts',
		'!**/modules/notifications/notification.factory.ts',
		'!**/modules/ai-assistant/chatgpt.service.ts',
		'!**/modules/ai-assistant/ai-settings.service.ts',
		'!**/scraper.*',
		'!**/scripts/**',
		'!**/src/config.ts',
	],
	coverageThreshold: {
		'./src/**/*.ts': {
			lines: 85,
		},
		'./modules/**/*.ts': {
			lines: 85,
		},
	},
};

module.exports = customJestConfig;
