services:
  zentra-api:
    image: zentra-api
    container_name: local-zentra-api-1
    build:
      context: ../../..
      dockerfile: finance-bot/docker/local/Dockerfile
    ports:
      - "${PORT:-5001}:5001"
    volumes:
      - ../../../finance-bot:/app/finance-bot
      - /app/finance-bot/node_modules
      - /app/finance-bot/dist
    environment:
      - DATABASE_URL=mysql://root:d!YG19j06eXp@local-mysql-zentra-1:3306/zentra
      - REDIS_URL=redis://redis-zentra:6379
      - PORT=5001
      - NODE_ENV=development
    networks:
      - zentra-network
    depends_on:
      - mysql-zentra
      - redis-zentra

networks:
  zentra-network:
    name: zentra-network
    external: true
