services:
  zentra-image-extractor:
    image: zentra-image-extractor
    container_name: local-zentra-image-extractor-1
    build:
      context: ../../services/image_recognition_service
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - zentra-network

networks:
  zentra-network:
    name: zentra-network
    external: true
