services:
  finance-bot-ui:
    image: finance-bot-ui
    build:
      context: ../../../finance-bot-ui
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=production
      - PORT=8080
      - NEXT_PUBLIC_API_URL=http://localhost:4001
    networks:
      - finance-bot-network
    depends_on:
      - express-bot-api
    restart: unless-stopped
