services:
  express-bot-api:
    image: express-api-bot
    platform: linux/amd64
    build:
      context: ../../
      dockerfile: docker/local/Dockerfile

    environment:
      - DATABASE_URL=mysql://root:d!YG19j06eXp@local-mysql-finance-bot-1:3306/finance-bot
    ports:
      - '4001:4001'
    networks:
      - finance-bot-network
    depends_on:
      - mysql-finance-bot
    volumes:
      - ../../:/app
      - /app/node_modules
