version: '3'

networks:
  finance-bot-network:
    driver: bridge

services:
  mysql-finance-bot:
    image: mysql
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: d!YG19j06eXp
      MYSQL_DATABASE: finance-bot
    ports:
      - '3308:3306'
    networks:
      - finance-bot-network
