version: '3'

services:
  mysql-development:
    image: mysql
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: d!YG19j06eXp
      MYSQL_DATABASE: finance-bot
    ports:
      - '3308:3306'
