version: '3'

networks:
  finance-bot-network:
    driver: bridge

services:
  mysql-finance-bot:
    image: mysql
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: d!YG19j06eXp
      MYSQL_DATABASE: finance-bot
    ports:
      - '3308:3306'
    networks:
      - finance-bot-network

  express-api-bot:
    image: express-api-bot
    platform: linux/amd64
    build:
      context: ../
      dockerfile: docker/Dockerfile

    environment:
      - DATABASE_URL=mysql://root:d!YG19j06eXp@mysql-finance-bot-1:3306/finance-bot
    ports:
      - '5000:5000'
    networks:
      - finance-bot-network
    depends_on:
      - mysql-finance-bot
