import Sinon from 'sinon';
import { calculateUSDAmountByRate, searchRateByDate } from './rate.helper';
import { createDailyExchangeRate } from '../../prisma/factories';
import { Decimal } from '@prisma/client/runtime/library';
import { prismaMock } from '../../modules/database/database.module.mock';
import { mockRedisClient } from '../../modules/database/redis.module.mock';

const sandbox = Sinon.createSandbox();

describe('searchRateByDate', () => {
	afterEach(() => {
		sandbox.resetHistory();
		sandbox.reset();
		sandbox.restore();
		jest.clearAllMocks();
	});
	// Returns a DailyExchangeRate object when a valid date is provided
	it('should return a DailyExchangeRate object when a valid date is provided', async () => {
		const validDate = '2022-01-01';
		const expectedRate = await createDailyExchangeRate({ id: 1, date: new Date('2022-01-01'), bcvPrice: new Decimal(1) });
		const mockFindFirst = prismaMock.dailyExchangeRate.findFirst.mockResolvedValue(expectedRate);

		const result = await searchRateByDate(validDate);

		expect(result).toEqual(expectedRate);
		expect(mockFindFirst).toHaveBeenCalledTimes(1);
	});

	// Returns null when no DailyExchangeRate object is found
	it('should return null when no DailyExchangeRate object is found', async () => {
		const validDate = '2022-01-01';

		const mockFindFirst = prismaMock.dailyExchangeRate.findFirst.mockResolvedValue(null);
		const result = await searchRateByDate(validDate);

		expect(result).toBeNull();
		expect(mockFindFirst).toHaveBeenCalledTimes(1);
	});

	it('should return a DailyExchangeRate object when no date is provided', async () => {
		const expectedRate = await createDailyExchangeRate({ id: 1, date: new Date('2022-01-01'), bcvPrice: new Decimal(1) });

		const mockFindFirst = prismaMock.dailyExchangeRate.findFirst.mockResolvedValue(expectedRate);

		const result = await searchRateByDate();

		expect(result).toEqual(expectedRate);
		expect(mockFindFirst).toHaveBeenCalledTimes(1);
	});

	it('should cache the exchange rate using node-redis v5 options syntax', async () => {
		const validDate = '2022-01-01';
		const expectedRate = await createDailyExchangeRate({ id: 1, date: new Date('2022-01-01'), bcvPrice: new Decimal(1) });
		mockRedisClient.get.mockResolvedValueOnce(null);
		prismaMock.dailyExchangeRate.findFirst.mockResolvedValue(expectedRate);

		await searchRateByDate(validDate);

		expect(mockRedisClient.set).toHaveBeenCalledWith(
			expect.stringContaining('exchange_rate:2022-01-01'),
			JSON.stringify(expectedRate),
			{ EX: 43200 }
		);
	});
});

// Generated by CodiumAI

describe('calculateUSDAmountByRate', () => {
	// Returns a number when given valid input values.
	it('should return the correct USD amount when given valid input values', () => {
		// Arrange
		const originalCurrencyAmount = 100;
		const bcvPrice = 10;

		// Act
		const result = calculateUSDAmountByRate(originalCurrencyAmount, bcvPrice);

		// Assert
		expect(result).toBe(10);
	});

	// Returns NaN when given NaN input values.
	it('should return NaN when given NaN input values', () => {
		// Arrange
		const originalCurrencyAmount = NaN;
		const bcvPrice = NaN;

		// Act
		const result = calculateUSDAmountByRate(originalCurrencyAmount, bcvPrice);

		// Assert
		expect(result).toBeNaN();
	});
});
