services:
  zentra-image-extractor-production:
    image: zentra-image-extractor-production
    container_name: zentra-image-extractor-production
    build:
      context: ../../services/image_recognition_service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4000:4000"
    networks:
      - zentra-production-network

networks:
  zentra-production-network:
    name: zentra-production-network
    external: true
