version: '3'

networks:
  finance-bot-production-network:
    driver: bridge

services:
  express-bot-production-api:
    image: express-api-bot
    platform: linux/amd64
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile

    env_file:
      - ../../.env
    ports:
      - '5000:5000'
    networks:
      - finance-bot-production-network
