services:
  mysql-zentra-production:
    image: mysql:8.0
    container_name: zentra-mysql-production
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: zentra
    ports:
      - "3306:3306"
    networks:
      - zentra-production-network
    volumes:
      - mysql_data:/var/lib/mysql

  redis-zentra-production:
    image: redis:alpine
    container_name: zentra-redis-production
    restart: always
    ports:
      - "6379:6379"
    networks:
      - zentra-production-network

networks:
  zentra-production-network:
    name: zentra-production-network
    driver: bridge

volumes:
  mysql_data:
