services:
  zentra-api-production:
    image: zentra-api-production
    container_name: zentra-api-production
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD}@zentra-mysql-production:3306/zentra
      - REDIS_URL=redis://zentra-redis-production:6379
      - PORT=5000
      - NODE_ENV=production
      - IMAGE_2_TEXT_SERVICE_URL=http://zentra-image-extractor-production:4000
    networks:
      - zentra-production-network
    depends_on:
      - mysql-zentra-production
      - redis-zentra-production

networks:
  zentra-production-network:
    name: zentra-production-network
    external: true
