version: '3'

networks:
  finance-bot-network:
    driver: bridge

services:
  mysql-finance-bot:
    image: mysql
    platform: linux/amd64
    env_file:
      - ./.env.db

    ports:
      - '3308:3306'
    networks:
      - finance-bot-network
