name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Set Port for tests
        run: |
          echo ${{ vars.PORT }} > .env

      - name: Test
        run: npm run test

      - name: Deploy
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.DROPLET_IP }} << EOF
            cd /www/var/bot.my-finance-app.xyz/
            git pull origin master
            ./deploy.sh production
          EOF
