name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm run test

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.DROPLET_IP }} << EOF
            cd /var/www/bot.my-finance-app.xyz/
            ls -la
            git pull
            chmod +x ./deploy.sh
            ./deploy.sh production
          EOF
