name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm run test

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            eval "$(ssh-agent -s)"
            ssh-add - <<< "${{ secrets.SSH_KEY }}"
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            cd /var/www/bot.my-finance-app.xyz/
            ssh -vT git@github.com
            git pull 
            echo "Cleaning docker system"
            docker system prune -f
            echo "Done!"

            # Build the docker image
            echo "Building docker image..."
            npm run docker:build

            # Start the docker container
            echo "Starting docker container..."
            npm run docker:start

            # Run the Prisma migration
            echo "Running Prisma migration..."
            npm run docker:migrations
            npm run docker:migrations-dev

            # Print the deployment status
            echo "Deployment successful!"
