name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Set Port for tests
        run: |
          echo ${{ vars.PORT }} > .env

      - name: Test
        run: npm run test

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /var/www/bot.my-finance-app.xyz/
            ls -la
            git pull
            chmod +x ./deploy.sh
            ./deploy.sh production
